-- MySQL Script generated by MySQL Workbench
-- Tue May  5 13:29:46 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cub_zu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cub_zu` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `cub_zu` ;

-- -----------------------------------------------------
-- Table `cub_zu`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`admins` (
  `adminid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `pass` VARCHAR(64) NOT NULL,
  `claim` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`adminid`),
  UNIQUE INDEX `pid_UNIQUE` (`adminid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_zu`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`providers` (
  `prvid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `prvname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastetl` DATETIME NULL DEFAULT NULL,
  `taxrate` FLOAT(3,1) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`prvid`),
  UNIQUE INDEX `prvid_UNIQUE` (`prvid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_zu`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`teams` (
  `teamid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `teamname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`teamid`),
  UNIQUE INDEX `teamid_UNIQUE` (`teamid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_zu`.`budgetdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`budgetdata` (
  `budgetid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `budget` INT(11) NOT NULL,
  `month` VARCHAR(8) NOT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`budgetid`),
  UNIQUE INDEX `pid_UNIQUE` (`budgetid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `budget_teamid` (`teamid` ASC),
  CONSTRAINT `budget_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_zu`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `budget_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_zu`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_zu`.`matchrules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`matchrules` (
  `ruleid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rank` TINYINT(4) NOT NULL,
  `groupname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `textmatch` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `scalefactor` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `scaleunit` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ruleid`),
  UNIQUE INDEX `ruleid_UNIQUE` (`ruleid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  CONSTRAINT `matchrules_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_zu`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_zu`.`metrictypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`metrictypes` (
  `metricid` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `metricname` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(48) NULL DEFAULT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`metricid`),
  UNIQUE INDEX `metricid_UNIQUE` (`metricid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  CONSTRAINT `metrictypes_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_zu`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_zu`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`projects` (
  `prjid` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `extname` VARCHAR(255) NULL DEFAULT NULL,
  `extid` VARCHAR(255) NULL DEFAULT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`prjid`),
  UNIQUE INDEX `pid_UNIQUE` (`prjid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `teamid_idx` (`teamid` ASC),
  CONSTRAINT `prj_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_zu`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prj_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_zu`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_zu`.`metricdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cub_zu`.`metricdata` (
  `id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `metric` SMALLINT(6) UNSIGNED NOT NULL,
  `data` BIGINT(20) UNSIGNED NOT NULL,
  `prjid` SMALLINT(6) UNSIGNED NOT NULL,
  `cost` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_Datetime` (`datetime` ASC),
  INDEX `pid_idx` (`prjid` ASC),
  INDEX `metricid_idx` (`metric` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `teamid_idx` (`teamid` ASC),
  CONSTRAINT `metricdata_metricid`
    FOREIGN KEY (`metric`)
    REFERENCES `cub_zu`.`metrictypes` (`metricid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_prjid`
    FOREIGN KEY (`prjid`)
    REFERENCES `cub_zu`.`projects` (`prjid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_zu`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_zu`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
