-- MySQL Script generated by MySQL Workbench
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cub_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cub_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cub_test` DEFAULT CHARACTER SET utf8 ;
USE `cub_test` ;

-- -----------------------------------------------------
-- Table `cub_test`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`admins` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`admins` (
  `adminid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `pass` VARCHAR(64) NOT NULL,
  `claim` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`adminid`),
  UNIQUE INDEX `pid_UNIQUE` (`adminid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`alertconst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`alertconst` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`alertconst` (
  `App_Limit` VARCHAR(255) NULL DEFAULT NULL,
  `Warning_Value` VARCHAR(255) NULL DEFAULT NULL,
  `Error_Value` VARCHAR(255) NULL DEFAULT NULL,
  `Boundary_Type` VARCHAR(255) NULL DEFAULT NULL,
  `Ext1` VARCHAR(255) NULL DEFAULT NULL,
  `Ext2` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`providers` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`providers` (
  `prvid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `prvname` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `lastetl` DATETIME NULL DEFAULT NULL,
  `taxrate` FLOAT(3,1) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`prvid`),
  UNIQUE INDEX `prvid_UNIQUE` (`prvid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_test`.`divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`divisions` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`divisions` (
  `divid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `divname` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`divid`),
  UNIQUE INDEX `divid_UNIQUE` (`divid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_test`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`teams` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`teams` (
  `teamid` TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `teamname` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `divid` TINYINT(4) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`teamid`),
  UNIQUE INDEX `teamid_UNIQUE` (`teamid` ASC),
  INDEX `divid_idx` (`divid` ASC),
  CONSTRAINT `divid`
    FOREIGN KEY (`divid`)
    REFERENCES `cub_test`.`divisions` (`divid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_test`.`budgetdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`budgetdata` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`budgetdata` (
  `budgetid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `budget` INT(11) NOT NULL,
  `month` VARCHAR(8) NOT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `response` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`budgetid`),
  UNIQUE INDEX `pid_UNIQUE` (`budgetid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `budget_teamid` (`teamid` ASC),
  UNIQUE KEY `month` (`month`, `prvid`, `teamid`),
  CONSTRAINT `budget_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_test`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `budget_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_test`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`matchrules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`matchrules` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`matchrules` (
  `ruleid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rank` TINYINT(4) NOT NULL,
  `groupname` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `textmatch` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `scalefactor` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `scaleunit` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`ruleid`),
  UNIQUE INDEX `ruleid_UNIQUE` (`ruleid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  CONSTRAINT `matchrules_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_test`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cub_test`.`metrictypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`metrictypes` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`metrictypes` (
  `metricid` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `metricname` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(48) NULL DEFAULT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`metricid`),
  UNIQUE INDEX `metricid_UNIQUE` (`metricid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  CONSTRAINT `metrictypes_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_test`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`projects` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`projects` (
  `prjid` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `extname` VARCHAR(255) NULL DEFAULT NULL,
  `extid` VARCHAR(255) NULL DEFAULT NULL,
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`prjid`),
  UNIQUE INDEX `pid_UNIQUE` (`prjid` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `teamid_idx` (`teamid` ASC),
  CONSTRAINT `prj_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_test`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prj_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_test`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`metricdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`metricdata` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`metricdata` (
  `id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `metric` SMALLINT(6) UNSIGNED NOT NULL,
  `data` BIGINT(20) UNSIGNED NOT NULL,
  `prjid` SMALLINT(6) UNSIGNED NOT NULL,
  `cost` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `prvid` TINYINT(4) UNSIGNED NOT NULL,
  `teamid` TINYINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_Datetime` (`datetime` ASC),
  INDEX `pid_idx` (`prjid` ASC),
  INDEX `metricid_idx` (`metric` ASC),
  INDEX `prvid_idx` (`prvid` ASC),
  INDEX `teamid_idx` (`teamid` ASC),
  CONSTRAINT `metricdata_metricid`
    FOREIGN KEY (`metric`)
    REFERENCES `cub_test`.`metrictypes` (`metricid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_prjid`
    FOREIGN KEY (`prjid`)
    REFERENCES `cub_test`.`projects` (`prjid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_prvid`
    FOREIGN KEY (`prvid`)
    REFERENCES `cub_test`.`providers` (`prvid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metricdata_teamid`
    FOREIGN KEY (`teamid`)
    REFERENCES `cub_test`.`teams` (`teamid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cub_test`.`perfconst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cub_test`.`perfconst` ;

CREATE TABLE IF NOT EXISTS `cub_test`.`perfconst` (
  `TimeOfDay` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web_http_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mapi_http_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `api_http_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mongo_web_mult` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web_order_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web_pv_mult` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mobile_pv_mult` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mobile_order_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `api_order_ratio` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web_ratio_mod` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `api_ratio_mod` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `web_order_mod` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mobile_order_mod` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `api_order_mod` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- --------------------------------------------------
-- Set up test teams, divisions, etc.
-- --------------------------------------------------

INSERT into cub_test.divisions (divname) VALUES ('Test-Tech');
INSERT into cub_test.divisions (divname) VALUES ('Test-Mkt');
INSERT into cub_test.teams (teamname, divid) VALUES ('Test-Team1', 1);
INSERT into cub_test.teams (teamname, divid) VALUES ('Test-Team2', 1);
INSERT into cub_test.teams (teamname, divid) VALUES ('Test-Team3', 2);
INSERT into cub_test.providers (prvname, taxrate) VALUES ('Test-Provider', 0.0);
INSERT into cub_test.providers (prvname, taxrate) VALUES ('Test-Provider-Mkt', 0.0);
INSERT into cub_test.projects (extname, extid, prvid, teamid) 
     VALUES ('Test-Project1', 'Testing123', 1, 1);
INSERT into cub_test.projects (extname, extid, prvid, teamid) 
     VALUES ('Test-Project2', 'Testing456', 1, 2);
INSERT into cub_test.projects (extname, extid, prvid, teamid) 
     VALUES ('Test-Mkt', 'Marketing', 2, 3);
INSERT into cub_test.metrictypes (metricname, unit, prvid) 
     VALUES ('mysql', 'day', 1);
INSERT into cub_test.metrictypes (metricname, unit, prvid) 
     VALUES ('sorcery', 'day', 2);
INSERT into cub_test.metricdata (datetime, metric, data, prjid, cost, prvid,
     teamid) VALUES ('2014-01-01 00:00:00', 1, 86400, 1, 20.00, 1, 1);
INSERT into cub_test.metricdata (datetime, metric, data, prjid, cost, prvid,
     teamid) VALUES ('2014-01-01 00:00:00', 1, 86400, 2, 40.00, 1, 2);
INSERT into cub_test.metricdata (datetime, metric, data, prjid, cost, prvid,
     teamid) VALUES ('2014-01-01 00:00:00', 2, 86400, 3, 80.00, 2, 3);
INSERT into cub_test.budgetdata (budget, month, prvid, teamid)
     VALUES (20, '2014-01', 1, 1);
INSERT into cub_test.budgetdata (budget, month, prvid, teamid)
     VALUES (50, '2014-01', 1, 2);
INSERT into cub_test.budgetdata (budget, month, prvid, teamid)
     VALUES (100, '2014-01', 2, 3);

